[build]
  publish = "agreeable-reservation-488504.framer.app_tostatic"
  command = ""

[dev]
  command = "npm run dev"
  targetPort = 5173
  publish = "agreeable-reservation-488504.framer.app_tostatic"
